const express = require("express");
const router = express.Router();

const tarotCards = [
  {
    name: "The Fool",
    name_vi: "Chàng Khờ",
    description: "The card suggests that your investments have the potential to yield positive results. The Fool signifies new beginnings, taking risks, and embracing unconventional approaches. It encourages you to trust your instincts and explore new opportunities. However, it's important to exercise caution and avoid recklessness.\n\nThe Fool card indicates that success may come through a sense of adventure and learning from both positive and negative outcomes. Overall, the card implies that your investments have a promising outlook, but the ultimate result will depend on your willingness to embrace the journey and make informed decisions.",
    description_vi: "Lá bài cho thấy các khoản đầu tư của bạn có tiềm năng mang lại kết quả tích cực. The Fool tượng trưng cho sự khởi đầu mới, dám chấp nhận rủi ro và đón nhận các phương pháp tiếp cận độc đáo. Nó khuyến khích bạn tin tưởng vào bản năng của mình và khám phá những cơ hội mới. Tuy nhiên, điều quan trọng là phải thận trọng và tránh liều lĩnh.\n\nThe Fool chỉ ra rằng thành công có thể đến thông qua ý thức phiêu lưu và học hỏi từ cả kết quả tích cực lẫn tiêu cực. Nhìn chung, lá bài ngụ ý rằng các khoản đầu tư của bạn có triển vọng đầy hứa hẹn, nhưng kết quả cuối cùng sẽ phụ thuộc vào sự sẵn sàng của bạn để nắm bắt hành trình và đưa ra các quyết định sáng suốt.",
    image: "/tarotdeck/thefool.jpeg",
  },
  {
    name: "The Magician",
    name_vi: "Pháp Sư",
    description: "The card suggests that your trades have the potential to yield successful results. The Magician represents power, skill, and manifestation of goals. It signifies that you have the necessary tools and abilities to make your investments profitable. This card encourages you to utilize your intellect, creativity, and resourcefulness to your advantage.\n\nBy harnessing your potential and making strategic decisions, you can manifest positive outcomes in your crypto trades. However, it's important to remember that the ultimate result will depend on your actions, choices, and market conditions. The Magician card indicates that you have the ability to influence and shape the outcome of your trades through your knowledge and skills.",
    description_vi: "Lá bài cho thấy các giao dịch của bạn có tiềm năng mang lại kết quả thành công. The Magician đại diện cho sức mạnh, kỹ năng và khả năng hiện thực hóa mục tiêu. Nó biểu thị rằng bạn có các công cụ và khả năng cần thiết để làm cho các khoản đầu tư của mình sinh lời. Lá bài này khuyến khích bạn sử dụng trí tuệ, sự sáng tạo và sự tháo vát của mình để tạo lợi thế.\n\nBằng cách khai thác tiềm năng của mình và đưa ra các quyết định chiến lược, bạn có thể thể hiện những kết quả tích cực trong các giao dịch tiền điện tử của mình. Tuy nhiên, điều quan trọng cần nhớ là kết quả cuối cùng sẽ phụ thuộc vào hành động, lựa chọn và điều kiện thị trường của bạn.",
    image: "/tarotdeck/themagician.jpeg",
  },
  {
    name: "The High Priestess",
    name_vi: "Nữ Tư Tế",
    description: "According to The High Priestess tarot card, your trades have the potential to yield mysterious and intuitive results. Trust your instincts, tap into hidden knowledge, and explore alternative perspectives to make informed decisions. The card suggests that unseen factors may influence your investments, and embracing your intuition can lead to profitable outcomes.\n\nHowever, remember that the High Priestess card doesn't guarantee specific results; success depends on your ability to navigate the market's mysteries using a blend of rational analysis and intuitive insights.",
    description_vi: "Theo lá Nữ Tư Tế, các giao dịch của bạn có tiềm năng mang lại những kết quả bí ẩn và trực quan. Hãy tin vào bản năng của bạn, khai thác kiến thức tiềm ẩn và khám phá các quan điểm thay thế để đưa ra các quyết định sáng suốt. Lá bài gợi ý rằng các yếu tố vô hình có thể ảnh hưởng đến các khoản đầu tư của bạn, và việc nắm bắt trực giác của bạn có thể dẫn đến những kết quả sinh lời.\n\nTuy nhiên, hãy nhớ rằng lá High Priestess không đảm bảo kết quả cụ thể; sự thành công phụ thuộc vào khả năng bạn điều hướng các bí ẩn của thị trường bằng cách sử dụng kết hợp phân tích lý trí và sự sáng suốt trực quan.",
    image: "/tarotdeck/thehighpriestess.jpeg",
  },
  {
    name: "The Empress",
    name_vi: "Nữ Hoàng",
    description: "According to The Empress tarot card, your trades have the potential to yield abundant and fruitful results. The Empress represents growth, nurturing, and prosperity. This card suggests that your investments may bring about positive outcomes and financial abundance. \n\nTo maximize your chances of success, it advises you to adopt a nurturing mindset and approach your trades with patience and care. Trust your in stincts and tap into your creativity when making decisions in the crypto market. By finding a harmonious balance between intuition and practicality, you can create favorable conditions for your investments to flourish.\n\nHowever, it's important to note that the Empress card does not guarantee specific outcomes. The actual results will depend on your actions, strategies, and the overall market conditions. Nevertheless, by embracing a nurturing mindset and making informed choices, you increase the likelihood of achieving prosperous results in your trading endeavors.",
    description_vi: "Theo lá bài Tarot Nữ Hoàng, các giao dịch của bạn có tiềm năng mang lại kết quả dồi dào và nhiều quả ngọt. Nữ Hoàng đại diện cho sự phát triển, nuôi dưỡng và thịnh vượng. Lá bài này cho thấy các khoản đầu tư của bạn có thể mang lại kết quả tích cực và sự dư dả về tài chính.\n\nĐể đạt được thành công cao nhất, lá bài khuyên bạn nên áp dụng tư duy nuôi dưỡng và tiếp cận các giao dịch của mình với sự kiên nhẫn và cẩn thận.",
    image: "/tarotdeck/theempress.jpeg",
  },
  {
    name: "The Emperor",
    name_vi: "Hoàng Đế",
    description: "The Emperor tarot card represents authority, structure, and stability. It symbolizes a time of taking control and establishing a solid foundation for your trades. This card suggests that your investments have the potential to yield positive results through a disciplined and structured approach. It encourages you to exercise leadership and make well-informed decisions based on careful analysis and strategic planning.\n\nBy setting clear boundaries and maintaining a sense of control, you can create a stable framework for success in your trades. However, it is important to remain adaptable to market conditions and make adjustments as necessary to ensure continued growth and prosperity.",
    description_vi: "Lá bài Tarot Hoàng Đế đại diện cho quyền lực, cấu trúc và sự ổn định. Nó biểu tượng cho khoảng thời gian nắm quyền kiểm soát và thiết lập một nền tảng vững chắc cho các giao dịch của bạn. Lá bài này gợi ý rằng các khoản đầu tư của bạn có tiềm năng mang lại kết quả tích cực thông qua cách tiếp cận có kỷ luật và có cấu trúc.\n\nBằng cách thiết lập ranh giới rõ ràng và duy trì cảm giác kiểm soát, bạn có thể tạo ra một khuôn khổ ổn định để thành công.",
    image: "/tarotdeck/theemperor.jpeg",
  },
  {
    name: "The Hierophant",
    name_vi: "Giáo Hoàng",
    description: "According to The Hierophant tarot card, your trades have the potential to yield structured and traditional results. The Hierophant represents conformity, tradition, and established systems. This card suggests that your investments may benefit from following established guidelines and adopting a conservative approach.\n\nTo increase the likelihood of success, it advises seeking guidance from experienced individuals or experts in the crypto market. The Hierophant encourages adhering to established strategies, rules, and regulations when making trading decisions. By aligning yourself with trusted sources of knowledge and respecting traditional trading methods, you can navigate the market more effectively.\n\n However, it's important to note that the Hierophant card does not guarantee specific outcomes. The actual results will depend on your ability to apply traditional principles while considering market dynamics and adapting when necessary. By maintaining a balance between tradition and flexibility, seeking expert advice, and making informed decisions, you can enhance the potential for successful results in your trades.",
    description_vi: "Theo lá Giáo Hoàng, các giao dịch của bạn có tiềm năng mang lại kết quả theo cấu trúc và truyền thống. Giáo Hoàng đại diện cho sự tuân thủ, truyền thống và các hệ thống đã được thiết lập. Lá bài này gợi ý rằng các khoản đầu tư của bạn có thể được hưởng lợi từ việc tuân theo các hướng dẫn đã được thiết lập và áp dụng một cách tiếp cận thận trọng.",
    image: "/tarotdeck/thehierophant.jpeg",
  },
  {
    name: "The Lovers",
    name_vi: "Kẻ Đang Yêu",
    description: "According to 'The Lovers' tarot card, your trades have the potential to yield harmonious and positive results. The Lovers represent partnership, alignment, and choices based on personal values. This card suggests that your investments may thrive when you make decisions that resonate with your beliefs and values. It encourages you to consider both financial and emotional aspects of your trades, seek harmony, and make choices that align with your true desires.\n\nCollaboration and finding common ground with others in the crypto market may contribute to favorable outcomes. Trust your instincts, stay true to yourself, and make informed decisions to increase the likelihood of achieving positive results. However, it's important to note that the Lovers card does not guarantee specific outcomes. The actual results will depend on your ability to make decisions in alignment with your values and navigate the market with integrity.",
    description_vi: "Theo lá Kẻ Đang Yêu, các giao dịch của bạn có khả năng tạo ra kết quả hài hòa và tích cực. The Lovers đại diện cho sự hợp tác, sự liên kết, và những lựa chọn dựa trên các giá trị cá nhân. Lá bài này gợi ý rằng các khoản đầu tư của bạn có thể phát triển mạnh mẽ khi bạn đưa ra những quyết định cộng hưởng với niềm tin của mình.",
    image: "/tarotdeck/TheLovers.jpg",
  },
  {
    name: "The Chariot",
    name_vi: "Cỗ Xe Ngựa",
    description: "According to 'The Chariot' tarot card, your trades have the potential to yield victory and success. The Chariot represents determination, willpower, and assertiveness. It suggests that through focused and disciplined efforts, you can overcome challenges and obstacles in the crypto market. By setting clear goals, devising strategic plans, and executing them confidently, you increase your chances of achieving triumphant outcomes.\n\nHowever, it's important to note that the Chariot card does not guarantee specific results. Your ultimate success will depend on your ability to maintain focus, adapt to changing circumstances, and make informed decisions. Approach your trades with determination, discipline, and adaptability to enhance the potential for positive results.",
    description_vi: "Theo lá Cỗ Xe Ngựa, các giao dịch của bạn có khả năng mang lại chiến thắng và thành công. The Chariot đại diện cho lòng quyết tâm, ý chí, và sự quyết đoán. Nó cho thấy rằng thông qua nỗ lực tập trung và có kỷ luật, bạn có thể vượt qua các thách thức và trở ngại trên thị trường.",
    image: "/tarotdeck/thechariot.jpeg",
  },
  {
    name: "Strength",
    name_vi: "Sức Mạnh",
    description: "According to 'Strength' tarot card, your trades have the potential to yield strength and resilience. The Strength card represents courage, inner power, and the ability to overcome challenges. It suggests that by harnessing your inner strength and staying focused, you can navigate the crypto market with confidence and determination. This card advises you to trust your abilities, remain calm in turbulent times, and persistently pursue your investment goals.\n\nHowever, it's important to remember that the Strength card does not guarantee specific outcomes. Your ultimate success will depend on your ability to stay strong, make informed decisions, and adapt to market conditions. Approach your trades with confidence, trust in your abilities, and remain resilient to enhance the potential for positive results.",
    description_vi: "Theo lá Sức Mạnh, các giao dịch của bạn có tiềm năng mang lại sức mạnh và khả năng phục hồi. Lá bài Sức Mạnh đại diện cho lòng can đảm, sức mạnh nội tâm và khả năng vượt qua thử thách. Nó khuyên bạn hãy tin tưởng vào khả năng của mình, giữ bình tĩnh trong những thời khắc hỗn loạn và kiên trì theo đuổi các mục tiêu đầu tư.",
    image: "/tarotdeck/thestrength.jpeg",
  },
  {
    name: "The Hermit",
    name_vi: "Ẩn Sĩ",
    description: "according to 'The Hermit' tarot card, your trades may yield introspection and solitude. The Hermit represents wisdom, self-reflection, and seeking inner guidance. This card suggests that your investments may benefit from taking a step back, reflecting on your strategies, and seeking a deeper understanding of the crypto market.\n\nIt advises prioritizing self-analysis and introspection in your trading decisions. The Hermit encourages you to seek solitude to refine your strategies and make well-informed choices. By trusting your inner wisdom and taking a cautious approach, you can navigate the market more effectively.\n\nHowever, it's important to note that the Hermit card does not guarantee specific results. The actual outcomes will depend on your ability to embrace introspection, integrate your learnings, and make informed decisions. Approach your trades with wisdom, take time for reflection, and make thoughtful choices to increase the likelihood of favorable results.",
    description_vi: "Theo lá Ẩn Sĩ, các giao dịch của bạn có thể mang lại sự tự suy ngẫm và sự tĩnh lặng. Ẩn Sĩ đại diện cho sự khôn ngoan, tự xem xét, và tìm kiếm sự hướng dẫn từ bên trong. Lá bài này gợi ý rằng các khoản đầu tư của bạn có thể hưởng lợi từ việc lùi lại một bước, suy ngẫm về chiến lược của bạn, và tìm kiếm sự hiểu biết sâu sắc hơn về thị trường.",
    image: "/tarotdeck/thehermit.jpeg",
  },
  {
    name: "Wheel of Fortune",
    name_vi: "Bánh Xe Số Phận",
    description: "According to 'Wheel of Fortune' tarot card, your trades may yield unpredictable results. The Wheel of Fortune represents cycles and changes in life, indicating that your investments may be subject to the ups and downs of the crypto market. This card advises you to embrace both opportunities and challenges that come your way, as luck and circumstances play a role in your trading outcomes. It suggests being adaptable and open to new possibilities.\n\nKeep in mind that external factors can influence your trades, so staying informed and making flexible decisions is crucial. However, it's important to note that the Wheel of Fortune card does not guarantee specific results. The actual outcomes will depend on various factors and your ability to navigate the changes effectively.",
    description_vi: "Theo lá Bánh Xe Số Phận, các giao dịch của bạn có thể mang những kết quả khó đoán. Wheel of Fortune đại diện cho các chu kỳ và sự thay đổi trong cuộc sống, chỉ ra rằng các khoản đầu tư của bạn có thể chịu tác động của những thăng trầm. Lá bài khuyên bạn nên nắm bắt cả cơ hội và thách thức khi vận may và hoàn cảnh đóng một vai trò quan trọng trong kết quả giao dịch của bạn.",
    image: "/tarotdeck/wheeloffortune.jpeg",
  },
  {
    name: "Justice",
    name_vi: "Công Lý",
    description: "According to the 'Justice' tarot card, your trades may yield fair and balanced results. The Justice card represents fairness, truth, and accountability. It suggests that your investments will be influenced by the principle of cause and effect.\n\nTo increase your chances of success, the card advises making decisions based on careful analysis and objective reasoning, while considering ethical and legal aspects. By acting with integrity and fairness in your trading, you create the conditions for just outcomes.\n\nHowever, it's important to note that the Justice card does not guarantee specific results. The actual outcomes will depend on your ability to make informed decisions, consider multiple perspectives, and adapt to the market's fairness and fluctuations.\n\nApproach your trades with integrity, seek fair dealings, and make informed choices to increase the likelihood of achieving favorable and balanced results.",
    description_vi: "Theo lá bài Tarot Công Lý, các giao dịch của bạn có thể đem lại kết quả công bằng và cân bằng. Lá bài Công Lý đại diện cho sự công bằng, sự thật và tính trách nhiệm. Nó gợi ý rằng các khoản đầu tư của bạn sẽ chịu ảnh hưởng bởi nguyên lý nhân quả. Hãy hành động với sự liêm chính.",
    image: "/tarotdeck/justice.jpeg",
  },
  {
    name: "The Hanged Man",
    name_vi: "Người Treo Ngược",
    description: "According to 'The Hanged Man' tarot card, your trades may yield a period of suspension, sacrifice, and gaining a new perspective. The Hanged Man represents a time of pause and surrender, encouraging you to let go of old strategies or beliefs that may no longer serve you. By embracing this period of suspension and adopting an open mind, you can gain valuable insights and potentially achieve successful outcomes in your investments.\n\nHowever, it's important to note that the Hanged Man card does not guarantee specific results. The actual outcomes will depend on your ability to embrace the period of suspension, surrender to new perspectives, and make informed decisions as you navigate the crypto market. Approach your trades with patience, adaptability, and a willingness to let go of control to increase the likelihood of positive results.",
    description_vi: "Theo lá Người Treo Ngược, các giao dịch của bạn có thể trải qua một giai đoạn đình trệ, hy sinh và có được một góc nhìn mới. The Hanged Man đại diện cho một thời gian tạm dừng và buông xuôi, khuyến khích bạn buông bỏ các chiến lược cũ kỹ không còn tác dụng để có cái nhìn đột phá.",
    image: "/tarotdeck/thehangedman.jpeg",
  },
  {
    name: "Death",
    name_vi: "Cái Chết",
    description: "According to the 'Death' tarot card, your trades may yield transformation, endings, and new beginnings. The Death card represents significant change and letting go of the old. It advises releasing attachments to outdated strategies or investments that no longer serve you. Embracing change and being adaptable can lead to positive outcomes in the long run.\n\nThe card suggests the potential for rebirth and renewal, signaling the need to let go of certain investments or approaches to make room for new opportunities. However, it's important to note that the Death card does not guarantee specific results. Your success will depend on your ability to embrace change, let go of the old, and make informed decisions as you navigate the crypto market. Approach your trades with an open mind and embrace transformation to increase the likelihood of positive results and new beginnings.",
    description_vi: "Theo lá bài Tarot Cái Chết, các giao dịch của bạn có thể trải qua sự biến đổi, những kết thúc và sự khởi đầu mới. Lá bài Death đại diện cho sự thay đổi đáng kể và việc buông bỏ cái cũ. Nó khuyên bạn nên từ bỏ sự bám chấp vào các chiến lược lỗi thời để dọn đường cho những cơ hội mới.",
    image: "/tarotdeck/death.jpeg",
  },
  {
    name: "Temperance",
    name_vi: "Tiết Chế",
    description: "According to the `Temperance` tarot card, your trades may yield balance, moderation, and harmony. The Temperance card represents finding the middle path and blending different elements together. It advises seeking a balanced approach, practicing moderation, and adapting to market conditions. By finding equilibrium between risk and caution, intuition and analysis, you increase the likelihood of positive outcomes. The card suggests that patient and steady trading, along with a harmonious mindset, can lead to favorable results. \n\nHowever, it's important to note that the Temperance card does not guarantee specific results. Your success will depend on your ability to find balance, exercise moderation, and make informed decisions. Approach your trades with a calm and balanced mindset, seek equilibrium in your strategies, and make choices that reflect a harmonious approach to increase the likelihood of favorable results.",
    description_vi: "Theo lá Tiết Chế, các giao dịch của bạn có thể mang lại sự cân bằng, chừng mực và hài hòa. Lá bài Temperance đại diện cho việc tìm ra con đường trung đạo và kết hợp các yếu tố khác nhau với nhau. Nó khuyên bạn nên tìm kiếm một cách tiếp cận cân bằng giữa rủi ro và thận trọng.",
    image: "/tarotdeck/temperance.jpeg",
  },
  {
    name: "The Devil",
    name_vi: "Ác Quỷ",
    description: "According to `The Devil` tarot card, your trades may yield entrapment, illusions, and negative outcomes. The Devil represents temptation, materialism, and being bound by unhealthy patterns or dependencies. This card suggests that your investments may be influenced by greed, impulsive decision-making, or falling into harmful practices.\n\nIt warns against making choices based solely on immediate gratification or following the herd mentality. The Devil card signifies the need to break free from limiting beliefs and take responsibility for your actions in the crypto market. By recognizing and releasing unhealthy attachments, you can avoid negative consequences and work towards more positive outcomes.\n\nHowever, it's important to note that the Devil card does not dictate a fixed result. Your ultimate outcome will depend on your ability to resist temptation, make informed decisions, and break free from harmful patterns. Approach your trades with caution, practice self-discipline, and seek clarity to increase the likelihood of achieving more favorable results.",
    description_vi: "Theo lá bài Tarot Ác Quỷ, các giao dịch của bạn có thể dẫn đến sự sập bẫy, ảo tưởng và kết quả tiêu cực. The Devil đại diện cho sự cám dỗ, chủ nghĩa vật chất, và việc bị ràng buộc bởi các khuôn mẫu hoặc sự phụ thuộc độc hại. Cảnh báo việc đưa ra những quyết định cảm tính, lòng tham hoặc theo tâm lý bầy đàn.",
    image: "/tarotdeck/thedevil.jpeg",
  },
  {
    name: "The Tower",
    name_vi: "Tòa Tháp",
    description: "According to `The Tower` tarot card, your trades may yield unexpected and disruptive results. The Tower represents sudden change, upheaval, and the breaking down of existing structures. It signifies a period of turmoil and transformation in your investment journey.\n\nThis card advises you to be prepared for unforeseen events that may shake the foundations of your trades. It signifies the need to adapt quickly to unexpected circumstances and make necessary adjustments. While the Tower represents a challenging period, it also presents an opportunity for growth and rebuilding.\n\nThe ultimate outcome will depend on your ability to navigate the upheaval and embrace change. It's important to remain resilient, seek opportunities amidst chaos, and make informed decisions in response to the new circumstances. Approach your trades with flexibility and adaptability to increase the likelihood of positive outcomes even in the face of disruption.",
    description_vi: "Theo lá Tòa Tháp, các giao dịch của bạn có thể mang lại những kết quả bất ngờ và mang tính phá vỡ. The Tower đại diện cho sự thay đổi đột ngột, những cuộc biến động, và sự sụp đổ của các cấu trúc hiện tại. Hãy chuẩn bị tinh thần cho những sự kiện bất ngờ có thể làm lung lay nền tảng các giao dịch của bạn.",
    image: "/tarotdeck/thetower.jpeg",
  },
  {
    name: "The Star",
    name_vi: "Ngôi Sao",
    description: "According to `The Star` tarot card, your trades may yield hope, inspiration, and positive outcomes. The Star represents a guiding light, offering a sense of optimism and renewal. It signifies that your investments have the potential to bring about positive changes and fulfill your aspirations.\n\nThis card advises you to stay focused on your goals and have faith in your abilities. It encourages you to trust the process and remain optimistic, even during challenging times. The Star suggests that by maintaining a positive mindset, being open to new possibilities, and aligning your actions with your aspirations, you can attract favorable results in your crypto trades. It symbolizes a sense of divine guidance and offers reassurance that your efforts will be rewarded.\n\nHowever, it's important to note that the Star card does not guarantee specific outcomes. The actual results will depend on your actions, market conditions, and your ability to stay committed to your goals. Embrace the hope and inspiration offered by the Star, stay aligned with your vision, and make informed decisions to increase the likelihood of positive and fulfilling results in your crypto trades.",
    description_vi: "Theo lá bài Tòa Ngôi Sao, các giao dịch của bạn có thể đem lại hy vọng, nguồn cảm hứng, và những kết quả tích cực. The Star đại diện cho ánh sáng dẫn đường, mang lại sự lạc quan và đổi mới. Nó biểu thị rằng các nỗ lực của bạn có tiềm năng mang lại những thay đổi tích cực và hoàn thành những ước mơ của bạn.",
    image: "/tarotdeck/thestar.jpeg",
  },
  {
    name: "The Moon",
    name_vi: "Mặt Trăng",
    description: "According to `The Moon` tarot card, your trades may yield results that are influenced by intuition, emotions, and the subconscious. The Moon represents the realm of the unknown, illusions, and hidden influences. It suggests that your investments may be subject to fluctuations and uncertainties in the crypto market. It advises you to trust your instincts and tap into your intuition when making trading decisions.\n\nHowever, be cautious of deceptive or misleading information and seek clarity through thorough research and analysis. The Moon reminds you to navigate the market with awareness, adaptability, and a balanced approach to emotions. While the outcomes may be unpredictable, by staying connected to your intuition and being mindful of the hidden aspects, you can make more informed choices to increase the likelihood of favorable results in your trades.",
    description_vi: "Theo lá bài Tarot Mặt Trăng, kết quả các giao dịch của bạn có thể bị ảnh hưởng bởi trực giác, cảm xúc và tiềm thức. The Moon đại diện cho cõi không tên, những ảo ảnh và các yếu tố che khuất. Khuyên bạn nên tin vào bản năng của mình, nhưng phải cẩn thận với thông tin lừa đảo.",
    image: "/tarotdeck/themoon.jpeg",
  },
  {
    name: "The Sun",
    name_vi: "Mặt Trời",
    description: "According to `The Sun` tarot card, your trades are likely to yield success, positivity, and abundance. The Sun represents joy, vitality, and favorable outcomes. It signifies a period of growth and flourishing in your investments.\n\nThis card advises you to have confidence in your abilities and embrace a positive mindset. It suggests that your investments have the potential to bring you happiness and financial rewards. The Sun card encourages you to seize opportunities, bask in the spotlight, and let your investments shine brightly.\n\nOverall, `The Sun` tarot card indicates that your trades are likely to yield optimistic and prosperous results. Embrace positivity, trust your instincts, and make informed decisions to enhance the potential for successful outcomes in the crypto market.",
    description_vi: "Theo lá bài Tarot Mặt Trời, các giao dịch của bạn có khả năng cao sẽ gặt hái thành công, sự tích cực và sự sung túc. The Sun đại diện cho niềm vui, sức sống và các kết quả vô cùng thuận lợi. Nó đánh dấu một giai đoạn thăng hoa và nở rộ trong các khoản đầu tư của bạn.",
    image: "/tarotdeck/thesun.jpeg",
  },
  {
    name: "Judgement",
    name_vi: "Phán Xét",
    description: "According to `The Judgement` tarot card, your trades may yield a significant period of evaluation, accountability, and potential rebirth. This card represents a call to reflect on your past choices and actions, and to make decisions based on a higher level of awareness. It signifies that your investments may undergo a period of scrutiny, where past decisions and their consequences will be brought to light.\n\nThis is an opportunity to assess your trading strategies, learn from any mistakes, and make adjustments for a fresh start. The Judgement card suggests that by embracing this period of evaluation and taking responsibility for your actions, you can potentially experience a rebirth and make more informed decisions that lead to positive outcomes in your trades.\n\nHowever, it's important to note that the Judgement card does not guarantee specific results. Your ultimate success will depend on your willingness to honestly assess your past choices, learn from them, and make well-informed decisions moving forward in the crypto market. Approach your trades with a sense of accountability and embrace this opportunity for growth and transformation.",
    description_vi: "Theo lá Phán Xét, các giao dịch của bạn có thể trải qua một giai đoạn đánh giá đáng kể, tính trách nhiệm và khả năng tái sinh. Lá bài này là một lời kêu gọi bạn hãy xem xét lại những lựa chọn và hành động đã qua trong quá khứ, đánh giá sai lầm để bắt đầu một chặng đường tươi mới.",
    image: "/tarotdeck/judgement.jpeg",
  },
  {
    name: "The World",
    name_vi: "Thế Giới",
    description: "According to `The World` tarot card, your trades are likely to yield successful and fulfilling results. The World represents completion, achievement, and wholeness. It signifies that your investments have the potential to reach a state of fulfillment and accomplishment. This card suggests that you have come full circle in your trading journey, and you are on the verge of experiencing positive outcomes and rewards. It signifies a sense of unity and integration, indicating that your trades may align with your overall goals and aspirations.\n\nThe World card encourages you to celebrate your achievements and embrace the opportunities that lie ahead. It represents a culmination of your efforts and suggests that your investments have the potential to make a significant impact in the crypto market. However, it's important to continue to stay grounded, adapt to changes, and maintain a balanced approach to sustain your success in the long term.",
    description_vi: "Theo lá Thế Giới, các giao dịch của bạn chắc chắn sẽ gặt hái được kết quả thành công rực rỡ và trọn vẹn. The World đại diện cho sự hoàn tất, thành tựu và sự toàn vẹn. Nó biểu thị rằng các khoản đầu tư của bạn đã đến đích của một hành trình chu kỳ và chuẩn bị bước vào giai đoạn tận hưởng chiến thắng.",
    image: "/tarotdeck/theworld.jpeg",
  },
  {
    name: "Ace of Cups",
    name_vi: "1 Cốc",
    description: "The `Ace of Cups` tarot card suggests that your trades may yield new opportunities and emotional fulfillment. This card represents the potential for new beginnings, abundance, and positive energy. It advises you to approach your investments with an open heart, allowing your intuition and emotions to guide you. The Ace of Cups signifies the potential for joy, fulfillment, and financial rewards in your trades.\n\nHowever, it's important to remember that the card does not guarantee specific results. The actual outcomes will depend on your ability to embrace new opportunities, listen to your intuition, and make informed decisions. Approach your trades with an open heart and align them with your highest values to increase the likelihood of positive and fulfilling results.",
    description_vi: "Các giao dịch của bạn có thể mang tới những cơ hội mới và sự trọn vẹn về cảm xúc. Nó hứa hẹn một sự khởi đầu tích cực với nguồn sinh lực dồi dào, đem lại cả niềm vui và tài chính.",
    image: "/tarotdeck/aceofcups.jpeg",
  },
  {
    name: "Two of Cups",
    name_vi: "2 Cốc",
    description: "According to the `Two of Cups` tarot card, your trades may yield positive and harmonious results. The Two of Cups represents partnerships, connections, and mutual benefits. It suggests that collaborating with others and seeking shared goals can enhance your chances of success in trading. By fostering open communication, trust, and emotional connections, you can create a sense of harmony and balance in your investments.\n\n However, it's important to note that the Two of Cups card does not guarantee specific results. The actual outcomes will depend on your ability to cultivate strong partnerships, communicate effectively, and make informed decisions. Approach your trades with a collaborative mindset, seek mutually beneficial arrangements, and nurture healthy relationships to increase the likelihood of favorable results.",
    description_vi: "Đại diện cho các mối quan hệ đối tác, sự kết nối và những lợi ích thiết thực song phương. Lời khuyên là tìm kiếm sự hợp tác bền vững để làm ăn và gặt hái kết quả hài hòa.",
    image: "/tarotdeck/twoofcups.jpeg",
  },
  {
    name: "Three of Cups",
    name_vi: "3 Cốc",
    description: "The `Three of Cups` tarot card suggests that your trades may yield positive and joyful results. This card represents celebration, friendship, and abundance. It indicates that your investments have the potential to bring about a sense of harmony, shared success, and fulfillment.\n\nThe card advises you to cultivate connections and collaborate with others in your trading endeavors. By working together and celebrating achievements, you can enhance your trading outcomes and create a supportive network.\n\nHowever, it's important to remember that the Three of Cups card does not guarantee specific results. The actual outcomes will depend on your ability to foster relationships, collaborate effectively, and make informed decisions in the crypto market.",
    description_vi: "Đại diện cho sự ăn mừng, tình bạn và sự dồi dào. Đầu tư có tiềm năng mang lại sự đồng thuận, thành công được sẻ chia cho nhiều người.",
    image: "/tarotdeck/threeofcups.jpeg",
  },
  {
    name: "Four of Cups",
    name_vi: "4 Cốc",
    description: "the `Four of Cups` tarot card, it suggests that your trades may yield a sense of contemplation and introspection. The Four of Cups represents a period of reflection, where you may find yourself feeling dissatisfied or uninterested with the current investment opportunities presented to you. It indicates a need to reassess your priorities and consider whether there are better options available.\n\n This card advises you to look beyond what is immediately in front of you and remain open to new possibilities. It urges you to examine your emotional state and desires in relation to your investments. It may be a time to take a step back, reevaluate your strategies, and consider whether there are alternative opportunities that align better with your goals.",
    description_vi: "Biểu hiện một thời kỳ trầm ngâm, một cảm giác không hài lòng hay chán nản với các cơ hội hiện có. Khuyên bạn hãy lùi lại một bước và đánh giá kỹ các kỳ vọng của bản thân.",
    image: "/tarotdeck/fourofcups.jpeg",
  },
  {
    name: "Five of Cups",
    name_vi: "5 Cốc",
    description: " The `Five of Cups` tarot card suggests that your trades may yield feelings of disappointment or loss. The Five of Cups represents a period of emotional upheaval and focusing on past failures or missed opportunities. It signifies that there may be setbacks or challenges in your investments, leading to a sense of regret or disillusionment. \n\nHowever, it's important to note that the Five of Cups also carries a message of learning and resilience. While there may be disappointment, it encourages you to acknowledge and process those emotions, but not dwell on them. It advises you to shift your focus from what went wrong to what can still be salvaged or learned from the situation.",
    description_vi: "Đại diện cho sự thất vọng hay chú tâm vào những thất bại, mất mát trong quá khứ. Tuy nhiên, nó cũng mang thông điệp của sự học hỏi và phục hồi.",
    image: "/tarotdeck/fiveofcups.jpeg",
  },
  {
    name: "Six of Cups",
    name_vi: "6 Cốc",
    description: "The `Six of Cups` tarot card suggest, that your trades may bring about a sense of nostalgia and past influences. The card suggests that your trades could be influenced by past experiences, memories, or connections. It could indicate a potential for revisiting familiar strategies or seeking opportunities rooted in the past. \n\nHowever, it's important to note that the prediction is based on symbolic interpretation and not an absolute guarantee of specific outcomes. The actual results will depend on various factors, including market conditions and your trading decisions.",
    description_vi: "Gợi ý về cảm giác hoài niệm và các yếu tố ảnh hưởng từ quá khứ. Bạn có thể sử dụng các kinh nghiệm, bài học cũ để dẫn lối cho các quyết định hiện tại.",
    image: "/tarotdeck/sixofcups.jpeg",
  },
  {
    name: "Seven of Cups",
    name_vi: "7 Cốc",
    description: "The `Seven of Cups` tarot card suggest, that the trader may face a period of confusion and overwhelming choices in their trades. The Seven of Cups represents a multitude of options and possibilities, but it also warns of the need for clarity and discernment.\n\n It suggests that the trader should be cautious and avoid getting lost in unrealistic or deceptive opportunities. It's important for the trader to carefully evaluate each option, stay focused on their goals, and make informed decisions to navigate through the complexity and make the most of their trading endeavors.",
    description_vi: "Đại diện cho sự bối rối vì có quá nhiều lựa chọn hoặc các hứa hẹn xa vời. Cảnh báo việc bạn bị mờ mắt trước lợi ích không thật, cần sự phân định rõ ràng.",
    image: "/tarotdeck/sevenofcups.jpeg",
  },
  {
    name: "Eight of Cups",
    name_vi: "8 Cốc",
    description: "The `Eight of Cups` tarot card suggest, that your trades may involve leaving behind certain investments or ventures. The Eight of Cups represents a period of transition and the need for emotional detachment from current circumstances. It implies that you may feel compelled to move on from certain trades or investment strategies in search of something more fulfilling or aligned with your goals.\n\nThe card advises you to trust your instincts and listen to your inner voice. It signifies that it might be necessary to let go of certain opportunities or investments that no longer serve you in order to pursue new paths and experiences.\n\nOverall, the prediction with the `Eight of Cups` card suggests a time of change and the need to explore new possibilities in your trading journey. It indicates that by leaving behind what no longer serves you, you can find greater fulfillment and growth in your future trades.",
    description_vi: "Biểu thị sự rời đi; bạn có khuynh hướng từ bỏ rũ bỏ những đầu tư không còn sinh lợi hoặc không phù hợp với mục tiêu sâu thẳm của mình.",
    image: "/tarotdeck/eightofcups.jpeg",
  },
  {
    name: "Nine of Cups",
    name_vi: "9 Cốc",
    description: "The `Nine Of Cups` tarot card suggests , that your trades have the potential to bring you fulfillment, satisfaction, and a sense of abundance. This card represents wishes fulfilled, emotional satisfaction, and overall positive outcomes. It suggests that your investments may lead to favorable results, bringing you joy and contentment.",
    description_vi: "Tiềm năng mang tới cho bạn sự mãn nguyện, hài lòng và dồi dào. Đại diện cho 'ước mơ thành hiện thực', các kết quả tích cực ngoài mong đợi.",
    image: "/tarotdeck/nineofcups.jpeg",
  },
  {
    name: "Ten of Cups",
    name_vi: "10 Cốc",
    description: "The `Ten of Cups` tarot card suggests , that your trades would be positive and fruitful. The Ten of Cups represents emotional fulfillment, harmony, and joy. It suggests that your investments have the potential to bring about a sense of contentment and satisfaction. This card indicates that your trades may lead to successful outcomes, not just in terms of financial gains, but also in terms of overall happiness and fulfillment.",
    description_vi: "Đại diện cho hạnh phúc đong đầy, hài hòa gia đạo, viên mãn trọn vẹn, không chỉ ở khía cạnh tiền bạc mà còn là niềm vui tận tâm can.",
    image: "/tarotdeck/tenofcups.jpeg",
  },
  {
    name: "Page of Cups",
    name_vi: "Tiểu Đồng Cốc",
    description: "The `Page of Cups` tarot card suggests that your trades may bring opportunities for emotional growth and new beginnings. The Page of Cups represents youthful enthusiasm, creativity, and the emergence of new ideas. It suggests that by approaching your trades with an open heart and a willingness to explore innovative strategies, you can potentially uncover profitable ventures or untapped potential in the crypto market.\n\nThis card encourages you to embrace your intuition, nurture your passions, and be open to unexpected opportunities that may arise. However, keep in mind that the Page of Cups card does not guarantee specific results, but rather signifies a potential for positive emotional and creative development in your trading journey.",
    description_vi: "Tràn đầy nhiệt huyết, ý tưởng mới mẻ và sự phát triển cảm xúc. Lời khuyên hãy giữ một trái tim rộng mở nếu muốn đầu tư sinh lợi bất ngờ.",
    image: "/tarotdeck/pageofcups.jpeg",
  },
  {
    name: "Knight of Cups",
    name_vi: "Hiệp Sĩ Cốc",
    description: "The `Knight of Cups` tarot card suggests that your trades may be guided by your emotional instincts, and there is potential for positive outcomes if you follow your heart and make decisions based on your intuition. It suggests that by combining your emotions with practicality and a balanced approach, you can navigate the crypto market successfully.\n\nHowever, it's important to note that the Knight of Cups card does not guarantee specific results. The actual outcomes will depend on your ability to harness your emotions effectively, make informed decisions, and maintain a level-headed approach in the face of market volatility.",
    description_vi: "Gợi ý việc nghe theo trực giác trong giao dịch nhưng cần giữ thăng bằng và thực tế tránh yếu tố chủ quan và cảm xúc lấn át lý trí.",
    image: "/tarotdeck/knightofcups.jpeg",
  },
  {
    name: "Queen of Cups",
    name_vi: "Nữ Hoàng Cốc",
    description: "The `Queen of Cups` card suggests that your investments may yield emotional fulfillment and intuitive success. The Queen of Cups represents emotional intelligence, compassion, and intuitive wisdom.\n\n It suggests that by tapping into your intuition, understanding your emotions, and making decisions from a place of empathy and compassion, you can navigate the crypto market with positive outcomes. Trust your instincts, remain emotionally balanced, and cultivate a deep understanding of the market to increase the likelihood of favorable results.",
    description_vi: "Trí tuệ cảm xúc, thấu cảm và sự khôn ngoan của trực giác. Đưa ra các quyết định sáng suốt từ một tư duy cân bằng.",
    image: "/tarotdeck/queenofcups.jpeg",
  },
  {
    name: "King of Cups",
    name_vi: "Vua Cốc",
    description: "The `King of Cups` suggests that your trades may result in emotional balance, intuitive decision-making, and potential financial success. The King of Cups represents emotional intelligence, stability, and a calm approach to your investments. It indicates that by tapping into your intuition and maintaining a balanced mindset, you have the potential to make wise decisions and achieve positive outcomes in the crypto market.",
    description_vi: "Sự bình ổn và bình tĩnh trước sóng gió thị trường. Thành công đến từ việc nắm vững tâm lý và kiểm soát cảm xúc tốt.",
    image: "/tarotdeck/kingofcups.jpeg",
  },
  {
    name: "Ace of Pentacles",
    name_vi: "1 Tiền",
    description: "The `Ace of Pentacles` suggests that your trades have the potential to yield new financial opportunities and material abundance. The Ace of Pentacles represents the beginning of prosperity and the manifestation of wealth. It suggests that your investments may lead to favorable outcomes, such as financial stability and growth. This card encourages you to seize these opportunities and make practical and grounded decisions in your trading activities.\n\n However, it's important to note that the card doesn't guarantee specific results, and the actual outcome will depend on various factors such as market conditions and your own actions. Approach your trades with a focused mindset, take advantage of the potential opportunities, and make informed choices to increase the likelihood of positive results.",
    description_vi: "Tiềm năng sinh lời cực cao, một khởi đầu mở ra sự thịnh vượng vật chất, của cải dồi dào. Hãy nắm bắt ngay các cơ hội chắc chắn.",
    image: "/tarotdeck/aceofpentacles.jpeg",
  },
  {
    name: "Two of Pentacles",
    name_vi: "2 Tiền",
    description: "The `Two of Pentacles` card suggests that your trades may involve balancing multiple financial responsibilities and finding harmony amidst changing circumstances. This card suggests that you will need to juggle different aspects of your investments, adapt to market fluctuations, and make practical decisions to maintain stability. The prediction implies that your ability to find balance and manage your resources wisely will be key to navigating the crypto market successfully.",
    description_vi: "Sự linh hoạt trong quản lý dòng tiền; bạn có thể đang tung hứng nhiều khoản cùng lúc, nhưng với kỹ năng thăng bằng thì mọi nguồn tài nguyên đều sẽ ổn.",
    image: "/tarotdeck/twoofpentacles.jpeg",
  },
  {
    name: "Three of Pentacles",
    name_vi: "3 Tiền",
    description: "The `Three of pentacles` suggests that your trades would be positive. The Three of Pentacles represents collaboration, skill, and success in your endeavors. It suggests that your trades have the potential to be fruitful, especially if you are willing to work with others and utilize your expertise.\n\n This card signifies the importance of teamwork, attention to detail, and honing your craft. It indicates that your efforts may be recognized, leading to rewards and progress in your trading journey. Overall, the tarot reader's prediction would be that your trades have the potential for success and prosperity.",
    description_vi: "Đại diện cho việc hợp tác kinh doanh, kỹ năng chuyên môn được đánh giá cao và sẽ có thành công vang dội khi kết nối làm ăn nhóm.",
    image: "/tarotdeck/threeofpentacles.jpeg",
  },
  {
    name: "Four of Pentacles",
    name_vi: "4 Tiền",
    description: "The `Four of Pentacles` represents a tendency to hold onto resources and maintain a secure financial position. It implies that you may be inclined to be cautious and reluctant to take risks in your trading activities. The card advises you to prioritize stability, financial security, and the preservation of your assets.\n\n However, it also indicates a potential need to find a balance between holding onto what you have and exploring new opportunities for growth. It suggests that while it's important to be mindful of financial stability, being too rigid or overly protective may hinder your potential for greater gains. Therefore, it is recommended to consider finding a balance between preserving your resources and taking calculated risks to maximize your trading outcomes.",
    description_vi: "Cẩn trọng về tài chính, bạn có xu hướng giữ khư khư tiền, nhưng hãy cẩn thận kẻo quá phòng thủ sẽ mất đi cơ hội đầu tư sinh lời.",
    image: "/tarotdeck/fourofpentacles.jpeg",
  },
  {
    name: "Five of Pentacles",
    name_vi: "5 Tiền",
    description: "The `Five of Pentacles` card suggest that your trades, the prediction would suggest potential financial challenges or difficulties. The Five of Pentacles represents a period of financial strain, scarcity, or feeling left out in the cold. It indicates that there may be losses or setbacks in your investments, and you might experience a sense of financial instability. \n\nHowever, it's important to note that the Tarot is not an absolute predictor of the future, and outcomes can be influenced by various factors. While the Five of Pentacles card suggests potential financial challenges, it is still within your power to take proactive steps, seek guidance, and adapt your strategies to improve the situation.",
    description_vi: "Báo động đỏ về thất thoát tài chính và khó khăn chật vật. Đừng ngần ngại tìm kiếm sự giúp đỡ bên ngoài thay vì chịu đựng sự hao hụt.",
    image: "/tarotdeck/fiveofpentacles.jpeg",
  },
  {
    name: "Six of Pentacles",
    name_vi: "6 Tiền",
    description: "The `Six of Pentacles` card suggests that your trades may experience a fair and balanced exchange. The Six of Pentacles represents generosity, reciprocity, and the flow of resources. It suggests that your trades have the potential to result in mutually beneficial outcomes, where you may receive support or assistance from others while also sharing your abundance with those in need. \n\nThis card indicates that your investments may lead to a harmonious and equitable distribution of wealth. However, it's important to note that the Six of Pentacles does not guarantee specific results. The actual outcomes will depend on various factors, including your actions, market conditions, and interactions with others. Approach your trades with a spirit of fairness, generosity, and integrity to increase the likelihood of positive and mutually beneficial results.",
    description_vi: "Đại diện cho sự trao đổi cân bằng, từ thiện và hào phóng. Bạn nhận lại tương xứng với những gì bỏ ra một cách minh bạch.",
    image: "/tarotdeck/sixofpentacles.jpeg",
  },
  {
    name: "Seven of Pentacles",
    name_vi: "7 Tiền",
    description: "The `Seven of Pentacles` card suggests that your trades would likely suggest a period of evaluation and patience. The Seven of Pentacles represents a time of reflection, assessing your investments, and waiting for the results to unfold. It indicates that your trades may require a patient approach, allowing your investments to grow and develop over time.\n\n The card advises you to review your progress, make necessary adjustments, and trust in the process of your investments. While it doesn't provide specific outcomes, it suggests that with careful assessment and patience, your trades have the potential to yield positive results in the long run.",
    description_vi: "Sự kiên nhẫn và nuôi dưỡng mầm non. Bạn đang xem xét thành quả và chỉ cần đợi thời cơ chín muồi để gặt hái sau chuỗi ngày làm việc vất vả.",
    image: "/tarotdeck/sevenofpentacles.jpeg",
  },
  {
    name: "Eight of Pentacles",
    name_vi: "8 Tiền",
    description: "The `Eight of Pentacles` card while you, as a crypto trader, ask about your trades, the prediction would be that your trades will likely result in focused effort, skill development, and potential financial gains. \n\nThe Eight of Pentacles represents dedication, hard work, and honing your expertise. It suggests that by putting in consistent effort, focusing on improving your skills, and staying committed to your trades, you have the potential to achieve success and financial growth in the crypto market.",
    description_vi: "Nêu cao sự cống hiến, tập trung trau dồi chuyên môn, nỗ lực làm việc đều đặn sẽ mang lại các đồng lời vững chãi, từ từ nhưng chắc chắn.",
    image: "/tarotdeck/eightofpentacles.jpeg",
  },
  {
    name: "Nine of Pentacles",
    name_vi: "9 Tiền",
    description: "The `Nine of Pentacles` card suggests that your trades have the potential to yield financial abundance and independent success. The Nine of Pentacles represents a time of prosperity, self-sufficiency, and reaping the rewards of your hard work. It indicates that your investments may result in financial stability and a sense of personal accomplishment.\n\nThis card encourages you to trust in your abilities, maintain a disciplined approach, and enjoy the fruits of your labor. It suggests that your trades may lead to a favorable outcome with the potential for financial growth and security.",
    description_vi: "Sự tự chủ và tận hưởng sự giàu có do chính đôi bàn tay mình làm ra. Sự độc lập tài chính bền vững.",
    image: "/tarotdeck/nineofpentacles.jpeg",
  },
  {
    name: "Ten of Pentacles",
    name_vi: "10 Tiền",
    description: "The `Ten of Pentacles` card suggests that your trades have the potential to bring substantial financial stability and long-term wealth. The Ten of Pentacles represents a culmination of material abundance, prosperity, and generational wealth. It suggests that your investments may yield significant returns and contribute to a solid financial foundation for yourself and possibly future generations. This card indicates that your trades have the potential to create a lasting and prosperous outcome, bringing you financial security and success in the crypto market.",
    description_vi: "Thành tựu tột bậc về sự trù phú vật chất, lợi ích dài hạn bền chắc, để lại nền móng tài sản vững chãi qua nhiều thế hệ.",
    image: "/tarotdeck/tenofpentacles.jpeg",
  },
  {
    name: "Page of Pentacles",
    name_vi: "Tiểu Đồng Tiền",
    description: "The `Page of Pentacles` card suggest that your trades as a crypto trader would be that there is potential for new financial opportunities and growth. The Page of Pentacles represents a young and ambitious individual who is eager to learn and apply their skills in practical ways.\n\n It suggests that by being diligent, focused, and open to learning, your trades have the potential to yield positive results, such as new investment prospects or profitable ventures. The card encourages you to approach your trades with a beginner's mindset, seeking knowledge and being willing to put in the necessary effort to achieve your financial goals.",
    description_vi: "Những cơ hội tươi mới mang tính hệ thống; người mới vào thị trường với thái độ học hỏi cẩn trọng rất dễ đạt mục tiêu dòng tiền.",
    image: "/tarotdeck/pageofpentacles.jpeg",
  },
  {
    name: "Knight of Pentacles",
    name_vi: "Hiệp Sĩ Tiền",
    description: "The `Knight of Pentacles` card suggests that with your trades you can expect steady and reliable progress. The Knight of Pentacles represents a methodical and disciplined approach, suggesting that your investments will yield gradual growth and stability. This card indicates that by focusing on long-term strategies, being diligent in your research, and taking a patient and practical approach, you have the potential to achieve financial stability and tangible results in your trades.",
    description_vi: "Sự tiến bộ chậm mà rất an toàn; cẩn thận soi xét đường đi nước bước để có lợi nhuận ổn định không rủi ro.",
    image: "/tarotdeck/knightofpentacles.jpeg",
  },
  {
    name: "Queen of Pentacles",
    name_vi: "Nữ Hoàng Tiền",
    description: "The `Queen of Pentacles` card suggest that your investments will likely bring stability, abundance, and financial success. The Queen of Pentacles represents a person or energy associated with practicality, nurturing, and material wealth. It suggests that your trading endeavors have the potential to generate positive outcomes, growth, and a strong foundation for your financial goals. It indicates that you may experience fruitful returns and a sense of security in your investment ventures.",
    description_vi: "Thực tế, bảo bọc, nuôi dưỡng thịnh vượng. Là nguồn lực dự phòng tốt tạo bàn đạp rất an tâm cho các quyết định đầu tư.",
    image: "/tarotdeck/queenofpentacles.jpeg",
  },
  {
    name: "King of Pentacles",
    name_vi: "Vua Tiền",
    description: "The `King of Pentacles` card suggests that your trades are likely to yield success, financial stability, and abundance. The `King of Pentacles` represents wealth, mastery, and practicality. It signifies that your investments have the potential to bring fruitful results and solid returns. This card suggests that you have the skills, knowledge, and expertise to make wise financial decisions in the crypto market. It advises you to approach your trades with a practical mindset, focus on long-term gains, and utilize your resources effectively. Overall, the prediction is that your trades have a high probability of leading to prosperous outcomes.",
    description_vi: "Quyền lực đỉnh điểm trên phương diện tài chính, tài khéo léo bậc thầy trong quản lý rủi ro trên thị trường thực.",
    image: "/tarotdeck/kingofpentacles.jpeg",
  },
  {
    name: "Ace of Swords",
    name_vi: "1 Kiếm",
    description: "The `Ace of Swords` card suggests that your trades have the potential to yield success, clarity, and breakthroughs. The Ace of Swords represents a new beginning, intellectual power, and the ability to make decisive and strategic decisions. It indicates that your trading activities may be marked by sharp insight, clear thinking, and a strong sense of purpose.\n\n This card signifies that you have the mental acuity and determination to overcome challenges and achieve your goals in the crypto market. It advises you to harness your intellectual prowess, embrace new opportunities, and take calculated risks to optimize your results. However, it's important to remember that tarot readings are interpretive, and the actual outcomes of your trades will depend on various factors and your own actions in the market.",
    description_vi: "Đại diện cho tính minh mẫn của trí tuệ, những rào cản sẽ bị phá tan bằng tư duy lập luận sắc bén nhất mang lại sự khai sáng và thắng lợi mới.",
    image: "/tarotdeck/aceofswords.jpeg",
  },
  {
    name: "Two of Swords",
    name_vi: "2 Kiếm",
    description: "The Two of Swords represents a situation where you may feel stuck, unable to move forward or make clear decisions. It suggests a period of uncertainty and conflicting options.\n\nThis card suggests that you are currently facing a dilemma in your trading decisions. It could be related to conflicting information, market volatility, or uncertainty about which path to take. The card advises you to carefully weigh your options, gather more information, and find a way to reconcile opposing factors before making any major trading decisions.\n\nHowever, it's important to note that the `Two of Swords` card does not provide a definitive outcome. The actual result of your trades will depend on your ability to confront the decision at hand, seek clarity, and make informed choices. The Tarot reader's prediction serves as a reminder to address the challenges and seek a resolution to move forward in your trading journey.",
    description_vi: "Khựng lại giữa ranh giới bất phân thắng bại; xung đột thông tin khiến bạn khó đưa ra quyết định giao dịch.",
    image: "/tarotdeck/twoofswords.jpeg",
  },
  {
    name: "Three of Swords",
    name_vi: "3 Kiếm",
    description: "The `Three of Swords` card suggests that in your trades this would be a period of heartache, pain, or difficulties. This card suggests that your investments may face challenges or setbacks that could potentially result in emotional turmoil or loss. It advises you to be prepared for difficult circumstances and to approach your trades with caution and careful consideration.\n\n However, it's important to remember that tarot readings are subjective and should be taken as guidance rather than a definitive prediction of the future. It's always wise to make decisions based on your own research, analysis, and risk assessment in the crypto market.",
    description_vi: "Nỗi đau khổ và những cú sốc thất vọng về đầu tư; hãy chấp nhận mất mát để tìm cách hồi phục và làm lại thay vì gục ngã.",
    image: "/tarotdeck/threeofswords.jpeg",
  },
  {
    name: "Four of Swords",
    name_vi: "4 Kiếm",
    description: "The `Four of Swords` card suggests this would be a period of rest, recuperation, and taking a break from active trading. It indicates that the best course of action at this time might be to step back and allow yourself some time for introspection and recharging.\n\n The card suggests that pushing forward with trades may not yield the desired results, and instead, it advises you to focus on self-care and regaining a sense of balance before resuming your trading activities.",
    description_vi: "Thời gian nghỉ ngơi, ngừng mọi giao dịch một lúc để não bộ 'xả hơi' lấy lại cân bằng cho tâm trí đang kiệt quệ.",
    image: "/tarotdeck/fourofswords.jpeg",
  },
  {
    name: "Five of Swords",
    name_vi: "5 Kiếm",
    description: "The `Five of Swords` card suggests potential conflict, competition, or challenges in your trades. The card indicates that you may encounter situations where you need to be cautious of deceit, manipulation, or unhealthy competition within the crypto market. It advises you to be strategic, maintain a sense of integrity, and carefully assess your decisions to navigate these challenging circumstances.",
    description_vi: "Môi trường đầy cạnh tranh tiêu cực, lừa gạt hoặc hao tài khi tham gia vào các trận chiến mà lợi ích chung không hề đáng giá.",
    image: "/tarotdeck/fiveofswords.jpeg",
  },
  {
    name: "Six of Swords",
    name_vi: "6 Kiếm",
    description: "The `Six of Swords` card suggests that your trades will bring about a period of transition, moving away from difficulties towards calmer waters. The card suggests that by making strategic decisions and leaving behind challenging situations, you can navigate towards a more stable and positive trading experience. This indicates a potential improvement in your trading journey, where you may find smoother sailing and a sense of relief from previous obstacles.",
    description_vi: "Quá trình rời bỏ giông bão để đi tìm sự êm ả. Lịch trình sẽ tĩnh lặng và khả quan hơn cho tương lai khoản đầu tư.",
    image: "/tarotdeck/sixofswords.jpeg",
  },
  {
    name: "Seven of Swords",
    name_vi: "7 Kiếm",
    description: "The `Seven of Swords` suggests that your trades may involve an element of deception, risk, or potential loss. The card suggests a need for caution and vigilance, as there could be hidden agendas, unethical practices, or potential theft in the trading environment. It advises you to be mindful of your actions, conduct thorough research, and take appropriate measures to protect your assets and interests. The Seven of Swords serves as a reminder to be skeptical of overly promising or questionable opportunities and to maintain a keen awareness of potential risks in your trading endeavors.",
    description_vi: "Cảnh báo gian lận, sự lừa dối ẩn giấu; đừng dính vào các phi vụ thiếu minh bạch và rủi ro trộm tiền cao.",
    image: "/tarotdeck/sevenofswords.jpeg",
  },
  {
    name: "Eight of Swords",
    name_vi: "8 Kiếm",
    description: "The `Eight of Swords` card suggest that your trades may experience a sense of feeling restricted or trapped in your investment endeavors. It signifies potential obstacles, limitations, or self-imposed restrictions that could hinder your progress or decision-making process.\n\nThis card advises you to examine any self-limiting beliefs or fears that may be holding you back. It urges you to challenge these constraints and seek ways to break free from the perceived limitations. By taking a proactive approach, seeking alternative perspectives, and overcoming self-doubt, you can navigate the challenges and find a path towards greater freedom and success in your trades.\n\nIn summary, the presence of the `Eight of Swords` card indicates the potential for feeling trapped or restricted in your trading journey. However, it also encourages you to confront and overcome these limitations by exploring new strategies and gaining a fresh perspective, ultimately leading to a path of greater freedom and success.",
    description_vi: "Tự rơi vào bế tắc bởi rào cản tư duy hạn hẹp của chính bản thân; tháo bỏ dải băng che mắt và nhìn mọi việc dưới góc độ cởi mở hơn sẽ tự giải quyết được.",
    image: "/tarotdeck/eightofswords.jpeg",
  },
  {
    name: "Nine of Swords",
    name_vi: "9 Kiếm",
    description: "The `Nine of Swords` card suggests that your investments may lead to feelings of worry, anxiety, or stress. The card serves as a cautionary sign to be mindful of potential challenges or difficulties. However, it's important to remember that tarot readings provide guidance, not fixed outcomes. By remaining calm, seeking support, and making informed choices, you can navigate the challenges and work towards more positive results.",
    description_vi: "Mất ngủ, chịu bao dằn vặt, lo lắng vì sợ rủi ro; hãy bình tĩnh phân tích vì đôi phần lỗi là do tâm lý quá căng thẳng.",
    image: "/tarotdeck/nineofswords.jpeg",
  },
  {
    name: "Ten of Swords",
    name_vi: "10 Kiếm",
    description: "The `Ten of Swords` card suggest that your trades may experience significant challenges or setbacks. The Ten of Swords represents a sense of defeat, betrayal, or reaching a low point in a situation. It signifies that your investments may face obstacles or unexpected negative outcomes.\n\nHowever, it's important to remember that Tarot predictions are not absolute and can be influenced by various factors. It's advisable to seek further guidance or explore different strategies to mitigate potential risks and navigate the challenging times in your trading journey.",
    description_vi: "Thất bại thảm hại, đã chạm đáy sự đau đớn khó lòng vãn hồi; tuy nhiên khi chạm đáy cũng chính là lúc chu kỳ mới sẽ bắt đầu mở ra.",
    image: "/tarotdeck/tenofswords.jpeg",
  },
  {
    name: "Page of Swords",
    name_vi: "Tiểu Đồng Kiếm",
    description: "The `Page of Swords` card suggest that your trades will require careful analysis, strategic planning, and an alert mindset. You should stay informed about market trends, be proactive in your decision-making, and adapt quickly to changes. By remaining curious, open-minded, and willing to take calculated risks, you can increase your chances of success in the crypto market.",
    description_vi: "Một trạng thái đầy học hỏi tò mò nhưng luôn theo dõi chặt chẽ thị trường. Cần cẩn trọng trong sự thích chứng tỏ năng lực.",
    image: "/tarotdeck/pageofswords.jpeg",
  },
  {
    name: "Knight of Swords",
    name_vi: "Hiệp Sĩ Kiếm",
    description: "The `Knight of Swords` card suggest that your trades may involve a period of rapid action, assertiveness, and taking risks. The Knight of Swords represents an ambitious and driven energy, indicating that you might pursue your trades with determination and a bold approach.\n\nHowever, it's important to exercise caution and ensure that you also consider the potential risks and consequences associated with impulsive decision-making. The card advises you to maintain a balance between swift action and careful consideration to achieve success in your trading endeavors.",
    description_vi: "Người có tốc độ như vũ bão, lao vào các thử thách rủi ro cao một cách táo bạo, hãy làm chậm lại nếu không muốn ngã ngựa.",
    image: "/tarotdeck/knightofswords.jpeg",
  },
  {
    name: "Queen of Swords",
    name_vi: "Nữ Hoàng Kiếm",
    description: "The `Queen of Swords` card suggest that your trades would need careful analysis, strategy, and maintaining a rational and objective approach. The Queen of Swords represents a sharp intellect, clear communication, and a focus on logic and reason. This card indicates that success in your trades will depend on your ability to make informed decisions based on thorough research and critical thinking.\n\nThe Queen of Swords encourages you to approach your trades with a level-headed mindset, relying on facts and data rather than emotions. By employing your analytical skills and maintaining a disciplined approach, you have the potential to make wise choices and achieve favorable outcomes in your investments.",
    description_vi: "Suy luận tỉnh táo và không để cảm xúc chi phối; một đầu óc phân tích dữ liệu siêu việt dẫn tới các quyết sách đúng đắn vô cùng logic.",
    image: "/tarotdeck/queenofswords.jpeg",
  },
  {
    name: "King of Swords",
    name_vi: "Vua Kiếm",
    description: "The `King of Swords` card suggest that your trades would likely be that you will experience a period of strategic decision-making, rationality, and intellectual prowess. The King of Swords represents a strong and analytical mindset, indicating that your trades may be influenced by a logical and calculated approach. It suggests that you have the potential to make informed and decisive choices in your investments, relying on your knowledge and expertise.\n\nThis card also signifies the importance of clear communication and assertiveness in your trading endeavors. In summary, the tarot reader's prediction with the `King of Swords` card suggests that your trades will be driven by logic, strategic thinking, and effective decision-making.",
    description_vi: "Người phán xét bậc thầy, năng lực tổng hợp và đánh giá thông tin vô cùng lý trí, là đỉnh cao của sự thông thái trong thương thuyết tài chính.",
    image: "/tarotdeck/kingofswords.jpeg",
  },
  {
    name: "Ace of Wands",
    name_vi: "1 Gậy",
    description: "The `Ace of Wands` card suggest that your trades have the potential to bring about new opportunities, creativity, and growth. The Ace of Wands represents the spark of inspiration, entrepreneurial spirit, and the initiation of successful ventures. It signifies that your trading activities may lead to exciting prospects, innovative ideas, and the potential for significant returns. It encourages you to take bold and decisive actions, harness your enthusiasm, and seize the opportunities that come your way. This card indicates that your trading journey holds promise and potential for successful outcomes.",
    description_vi: "Nguồn năng lượng khởi phát lớn, sức sáng tạo và niềm đam mê cuộn dâng, rất tốt với các đợt phát kiến các dự án đầu tư mới mẻ.",
    image: "/tarotdeck/aceofwands.jpeg",
  },
  {
    name: "Two of Wands",
    name_vi: "2 Gậy",
    description: "The `Two of Wands` card suggests that your trades would be a potential for future success and expansion. The Two of Wands represents making plans, envisioning opportunities, and taking bold steps towards your goals. It suggests that your trades have the potential to yield positive outcomes, growth, and new possibilities. It advises you to seize opportunities, trust your instincts, and take calculated risks in order to achieve your desired results. However, it's important to note that the actual outcome will depend on your actions, decisions, and market conditions. Embrace the card's message of confidence and forward-thinking as you navigate the crypto market.",
    description_vi: "Tầm nhìn xa trông rộng, một người đang lên chiến lược rõ ràng cho việc bành trướng quy mô đầu tư.",
    image: "/tarotdeck/twoofwands.jpeg",
  },
  {
    name: "Three of Wands",
    name_vi: "3 Gậy",
    description: "The `Three of Wands` card suggests that your trades have the potential for expansion, growth, and successful outcomes. The Three of Wands signifies taking a proactive approach, having a strategic vision, and being ready to explore new horizons in your investments. It suggests that your trades may lead to opportunities for long-term success, both in terms of financial gains and personal development. However, it's important to note that the actual results will depend on your ability to seize these opportunities, make informed decisions, and adapt to the evolving market conditions.",
    description_vi: "Sự mở rộng, tăng trưởng; chờ đợi con tàu chở hàng hóa lợi nhuận cập bến thành công tốt đẹp.",
    image: "/tarotdeck/threeofwands.jpeg",
  },
  {
    name: "Four of Wands",
    name_vi: "4 Gậy",
    description: "The `Four of Wands` card suggests that with your trades you can expect a period of stability, success, and celebration. The Four of Wands represents a time of achievement, harmony, and a solid foundation in your investments. It suggests that your trades have the potential to bring about positive outcomes, financial stability, and a sense of accomplishment. This card indicates that your efforts in the crypto market will likely be rewarded and that you may experience a period of fruitful results. Overall, the prediction is that your trades have the potential to yield favorable and prosperous outcomes.",
    description_vi: "Nền tảng vững chắc, kỳ nghỉ hân hoan chúc mừng một cột mốc thắng lợi an ổn đạt được trong kinh doanh.",
    image: "/tarotdeck/fourofwands.jpeg",
  },
  {
    name: "Five of Wands",
    name_vi: "5 Gậy",
    description: "The `Five of Wands` card, suggests that your trades may encounter competition, conflicts, or obstacles in your trading journey. The card indicates a period of challenges and disagreements within the market or among fellow traders. However, it's important to remember that the `Five of Wands` card does not guarantee specific outcomes. The actual results will depend on your ability to navigate the competitive landscape, overcome conflicts, and find ways to stand out amidst the challenges. Approach your trades with resilience, strategic thinking, and the willingness to adapt to increase the likelihood of favorable results.",
    description_vi: "Sự đấu tranh, cạnh tranh thị trường gay gắt, nhiều rắc rối nhưng nếu nhìn tích cực sẽ tạo được động lực đổi mới.",
    image: "/tarotdeck/fiveofwands.jpeg",
  },
  {
    name: "Six of Wands",
    name_vi: "6 Gậy",
    description: "The `Six of Wands` card suggests that your trades will be successful and bring you recognition and victory. The Six of Wands symbolizes triumph, achievement, and public recognition for your efforts. It suggests that your trades have the potential to yield positive outcomes and be met with acclaim from others. Overall, the prediction indicates that your investments have a high chance of being successful and bringing you significant rewards.",
    description_vi: "Đỉnh vinh quang, bạn được tán dương và đứng trên bục chiến thắng, sự thành công đã được đại chúng ghi nhận.",
    image: "/tarotdeck/sixofwands.jpeg",
  },
  {
    name: "Seven of Wands",
    name_vi: "7 Gậy",
    description: "The `Seven of Wands` card suggest that you will face challenges and competition in the crypto market. The card indicates that you will need to defend your position and assert yourself amidst potential obstacles. However, it also implies that with determination, resilience, and strategic decision-making, you have the ability to overcome these challenges and come out on top.",
    description_vi: "Một mình chống lại dư luận, phải kiên quyết bảo vệ vị thế của mình trước các cuộc tấn công và vất vả đối mặt với phe đối lập.",
    image: "/tarotdeck/sevenofwands.jpeg",
  },
  {
    name: "Eight of Wands",
    name_vi: "8 Gậy",
    description: "The `Eight of Wands` card, suggests that your trades would be swift and decisive action. The Eight of Wands represents a period of rapid progress, momentum, and opportunities coming your way. It suggests that your trades have the potential for quick movement, possibly resulting in profitable outcomes.\n\nThis card encourages you to seize the moment and act swiftly, as it signifies favorable conditions and an accelerated pace in the crypto market. However, it's important to note that the interpretation of tarot cards is subjective, and the actual outcomes of your trades will depend on various factors. Approach your trades with attentiveness, make informed decisions, and take advantage of the opportunities that arise to increase the likelihood of positive results.",
    description_vi: "Hành động nhanh gọn, tiến triển cực nhanh. Thông tin cập nhật từng giây từng phút mang tính sống còn đối với sự bắt nhịp thị trường.",
    image: "/tarotdeck/eightofwands.jpeg",
  },
  {
    name: "Nine of Wands",
    name_vi: "9 Gậy",
    description: "The `Nine of Wands` card suggest that your trades may encounter challenges and obstacles. The Nine of Wands represents resilience, perseverance, and the need to stay vigilant in the face of adversity. It indicates that you may need to protect your investments, be prepared for potential setbacks, and remain determined to overcome any obstacles that come your way. \n\nDespite the challenges, the card encourages you to stay committed to your goals and trust in your ability to navigate through difficulties. By maintaining your resilience and adaptability, you can increase the likelihood of successfully overcoming the hurdles and achieving positive outcomes in your trades.",
    description_vi: "Sự hao tổn sức lực, mỏi mệt nhưng vẫn quyết tâm ráng bảo vệ mọi thứ; một rào cản vững chắc ngăn sự thâm nhập của thất bại.",
    image: "/tarotdeck/nineofwands.jpeg",
  },
  {
    name: "Ten of Wands",
    name_vi: "10 Gậy",
    description: "The `Ten of Wands` card suggest that your trades may result in a heavy burden or overwhelming workload. It indicates that you might encounter challenges and responsibilities that could become exhausting and take a toll on your well-being. The card advises you to be mindful of taking on too much and to find ways to manage the stress that may arise from your trading activities. By maintaining a balanced approach and seeking support when needed, you can navigate the demands of trading more effectively.",
    description_vi: "Ôm đồm quá mức tới độ kiệt quệ với gánh nặng công việc đầu tư. Khuyên nên biết san sẻ đi.",
    image: "/tarotdeck/tenofwands.jpeg",
  },
  {
    name: "Page of Wands",
    name_vi: "Tiểu Đồng Gậy",
    description: "The `Page of Wands` card suggest that your trading will likely be in new opportunities where you will have enthusiasm, and potential for growth. The Page of Wands represents a fresh start, creative energy, and the willingness to explore new ventures. It suggests that your trades may bring about exciting prospects and a sense of passion in your investment journey. This card encourages you to embrace the enthusiasm, take calculated risks, and be open to innovative approaches. It signifies that by staying proactive, adaptable, and adventurous in your trading decisions, you may uncover promising avenues for success.",
    description_vi: "Tràn trề ý tưởng táo bạo nhưng thiếu thực thi. Sẵn lòng khám phá ranh giới mới nhưng rất dễ bị quá tải hoặc nản sau giai đoạn hào hứng.",
    image: "/tarotdeck/pageofwands.jpeg",
  },
  {
    name: "Knight of Wands",
    name_vi: "Hiệp Sĩ Gậy",
    description: "The `Knight of Wands` card suggests that your trades will be characterized by passion, energy, and a drive for action. The Knight of Wands signifies a period of taking bold and assertive steps in pursuit of your goals. It suggests that you will likely experience opportunities for growth and expansion in your trading activities. However, it's important to approach your trades with caution and ensure that you maintain a balance between enthusiasm and careful planning. The Knight of Wands encourages you to channel your energy and passion into focused and strategic actions to increase the likelihood of positive outcomes.",
    description_vi: "Táo bạo đầy lửa, một người thích hành động tức thời tiến công ngay lập tức theo phong cách ưa phiêu lưu liều lĩnh.",
    image: "/tarotdeck/knightofwands.jpeg",
  },
  {
    name: "Queen of Wands",
    name_vi: "Nữ Hoàng Gậy",
    description: "The `Queen of Wands` card suggests that your trades will likely result in confident and bold outcomes. The Queen of Wands represents a strong and determined individual who takes charge and exudes leadership qualities. It suggests that your investments may yield success through your ability to embrace opportunities, trust your instincts, and take decisive action. This card indicates that you have the potential to make significant strides in the crypto market by being passionate, assertive, and confident in your trading decisions.",
    description_vi: "Có khả năng truyền lửa, tự tin đầy cuốn hút và một tổ chức có tinh thần cực nhiệt huyết, mang năng lượng ấm áp.",
    image: "/tarotdeck/queenofwands.jpeg",
  },
  {
    name: "King of Wands",
    name_vi: "Vua Gậy",
    description: "The `King of Wands` card suggests that your trades would be one of ambition, energy, and success. The King of Wands represents a dynamic and confident leader who possesses entrepreneurial skills and a visionary mindset. This card suggests that your trades have the potential to be bold and profitable. It signifies that by harnessing your passion, taking decisive action, and leveraging your creativity, you can achieve significant success in your investments.\n\nHowever, it's important to remember that tarot readings are subjective and should be taken as guidance rather than absolute predictions. The actual outcomes will depend on your actions, market conditions, and other factors. Approach your trades with confidence, take calculated risks, and use your visionary skills to increase the likelihood of favorable results.",
    description_vi: "Khả năng lãnh đạo tầm nhìn, người kiến tạo đầy quyền lực, gặt hái thành công bằng sự tiên phong và lôi cuốn mọi người cùng đạt mục tiêu.",
    image: "/tarotdeck/kingofwands.jpeg",
  },
];

// Define the '/cards' endpoint to retrieve all cards
router.get("/", (req, res) => {
  res.json(tarotCards);
});

router.get("/onecard", (req, res) => {
  const randomIndex = Math.floor(Math.random() * tarotCards.length);
  const randomCard = tarotCards[randomIndex];
  res.json(randomCard);
});

module.exports = router;
